//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogsTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogsTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.LogsTranslations", typeof(LogsTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей выполнило ежедневное задание.
        /// </summary>
        internal static string PCDT {
            get {
                return ResourceManager.GetString("PCDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей собрало прибыль больше 3 раз.
        /// </summary>
        internal static string PCIMT {
            get {
                return ResourceManager.GetString("PCIMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей собрало прибыль 1-3 раза.
        /// </summary>
        internal static string PCIOTTT {
            get {
                return ResourceManager.GetString("PCIOTTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей задонатило.
        /// </summary>
        internal static string PD {
            get {
                return ResourceManager.GetString("PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей выставило стикер на аукцион.
        /// </summary>
        internal static string PPSTA {
            get {
                return ResourceManager.GetString("PPSTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей отправило хотя бы 1 стикер.
        /// </summary>
        internal static string PSSOOMT {
            get {
                return ResourceManager.GetString("PSSOOMT", resourceCulture);
            }
        }
    }
}
