//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogsTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogsTranslations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.Translations.LogsTranslations", typeof(LogsTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В каком количестве бесед был активен.
        /// </summary>
        internal static string GroupCountWasActive {
            get {
                return ResourceManager.GetString("GroupCountWasActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В скольких беседах был добавлен.
        /// </summary>
        internal static string GroupCountWasAdded {
            get {
                return ResourceManager.GetString("GroupCountWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сколько призов роздано за день.
        /// </summary>
        internal static string GroupPrizeCount {
            get {
                return ResourceManager.GetString("GroupPrizeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приглашенных пользователей.
        /// </summary>
        internal static string InvitedUsers {
            get {
                return ResourceManager.GetString("InvitedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей собрало прибыль больше 3 раз.
        /// </summary>
        internal static string PeopleCollectedIncomeMoreTimes {
            get {
                return ResourceManager.GetString("PeopleCollectedIncomeMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей собрало прибыль 1-3 раза.
        /// </summary>
        internal static string PeopleCollectedIncomeOneToThreeTimes {
            get {
                return ResourceManager.GetString("PeopleCollectedIncomeOneToThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей выполнило ежедневное задание.
        /// </summary>
        internal static string PeopleCompletedDailyTask {
            get {
                return ResourceManager.GetString("PeopleCompletedDailyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей задонатило.
        /// </summary>
        internal static string PeopleDonated {
            get {
                return ResourceManager.GetString("PeopleDonated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей выставило стикер на аукцион.
        /// </summary>
        internal static string PeoplePutsStickerToAuction {
            get {
                return ResourceManager.GetString("PeoplePutsStickerToAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людей отправило хотя бы 1 стикер.
        /// </summary>
        internal static string PeopleSendsStickerOneOrMoreTimes {
            get {
                return ResourceManager.GetString("PeopleSendsStickerOneOrMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество игр в рулетку.
        /// </summary>
        internal static string RoulettePlayCount {
            get {
                return ResourceManager.GetString("RoulettePlayCount", resourceCulture);
            }
        }
    }
}
