//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Commands.ChosenInlineResultHandler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChosenInlineResultCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChosenInlineResultCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Commands.ChosenInlineResultHandler.ChosenInlineResultCommands", typeof(ChosenInlineResultCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAK.
        /// </summary>
        internal static string add_puzzle {
            get {
                return ResourceManager.GetString("add_puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA.
        /// </summary>
        internal static string chat_send_sticker {
            get {
                return ResourceManager.GetString("chat_send_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAH.
        /// </summary>
        internal static string made_a_bet {
            get {
                return ResourceManager.GetString("made_a_bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAB.
        /// </summary>
        internal static string select_edit_sticker {
            get {
                return ResourceManager.GetString("select_edit_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAJ.
        /// </summary>
        internal static string select_puzzle {
            get {
                return ResourceManager.GetString("select_puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC.
        /// </summary>
        internal static string select_sticker {
            get {
                return ResourceManager.GetString("select_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD.
        /// </summary>
        internal static string select_trader {
            get {
                return ResourceManager.GetString("select_trader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAE.
        /// </summary>
        internal static string send_private_sticker {
            get {
                return ResourceManager.GetString("send_private_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAI.
        /// </summary>
        internal static string set_distribution_sticker {
            get {
                return ResourceManager.GetString("set_distribution_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAG.
        /// </summary>
        internal static string set_giveaway_channel {
            get {
                return ResourceManager.GetString("set_giveaway_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAF.
        /// </summary>
        internal static string set_giveaway_prize {
            get {
                return ResourceManager.GetString("set_giveaway_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAG.
        /// </summary>
        internal static string sticker_info {
            get {
                return ResourceManager.GetString("sticker_info", resourceCulture);
            }
        }
    }
}
