// <auto-generated />
using System;
using CardCollector.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardCollector.Migrations
{
    [DbContext(typeof(BotDatabaseContext))]
    [Migration("20220518220112_PuzzlePieces")]
    partial class PuzzlePieces
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CardCollector.Database.Entity.Auction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<long>("StickerId")
                        .HasColumnType("bigint")
                        .HasColumnName("sticker_id");

                    b.Property<long>("TraderId")
                        .HasColumnType("bigint")
                        .HasColumnName("trader_id");

                    b.HasKey("Id")
                        .HasName("pk_auctions");

                    b.HasIndex("StickerId")
                        .HasDatabaseName("ix_auctions_sticker_id");

                    b.HasIndex("TraderId")
                        .HasDatabaseName("ix_auctions_trader_id");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.ChannelGiveaway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ButtonText")
                        .HasColumnType("longtext")
                        .HasColumnName("button_text");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("ImageFileId")
                        .HasColumnType("longtext")
                        .HasColumnName("image_file_id");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    b.Property<int>("Prize")
                        .HasColumnType("int")
                        .HasColumnName("prize");

                    b.Property<int>("PrizeCount")
                        .HasColumnType("int")
                        .HasColumnName("prize_count");

                    b.Property<long?>("SelectedStickerId")
                        .HasColumnType("bigint")
                        .HasColumnName("selected_sticker_id");

                    b.Property<int?>("SelectedStickerTier")
                        .HasColumnType("int")
                        .HasColumnName("selected_sticker_tier");

                    b.Property<DateTime?>("SendAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("send_at");

                    b.HasKey("Id")
                        .HasName("pk_channel_giveaways");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_channel_giveaways_channel_id");

                    b.HasIndex("SelectedStickerId")
                        .HasDatabaseName("ix_channel_giveaways_selected_sticker_id");

                    b.ToTable("channel_giveaways", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.ChatDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Buttons")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("buttons");

                    b.Property<string>("ImageFileId")
                        .HasColumnType("longtext")
                        .HasColumnName("image_file_id");

                    b.Property<string>("StickerFileId")
                        .HasColumnType("longtext")
                        .HasColumnName("sticker_file_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_chat_distributions");

                    b.ToTable("chat_distributions", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.ChatRoulette", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_started");

                    b.Property<int>("MessageId")
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_chat_roulette");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_chat_roulette_creator_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_chat_roulette_group_id");

                    b.ToTable("chat_roulette", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.CountLogs", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("GroupCountWasActive")
                        .HasColumnType("int")
                        .HasColumnName("group_count_was_active");

                    b.Property<int>("GroupCountWasAdded")
                        .HasColumnType("int")
                        .HasColumnName("group_count_was_added");

                    b.Property<int>("GroupPrizeCount")
                        .HasColumnType("int")
                        .HasColumnName("group_prize_count");

                    b.Property<int>("InvitedUsers")
                        .HasColumnType("int")
                        .HasColumnName("invited_users");

                    b.Property<int>("PeopleCollectedIncomeMoreTimes")
                        .HasColumnType("int")
                        .HasColumnName("people_collected_income_more_times");

                    b.Property<int>("PeopleCollectedIncomeOneToThreeTimes")
                        .HasColumnType("int")
                        .HasColumnName("people_collected_income_one_to_three_times");

                    b.Property<int>("PeopleCompletedDailyTask")
                        .HasColumnType("int")
                        .HasColumnName("people_completed_daily_task");

                    b.Property<int>("PeopleDonated")
                        .HasColumnType("int")
                        .HasColumnName("people_donated");

                    b.Property<int>("PeoplePutsStickerToAuction")
                        .HasColumnType("int")
                        .HasColumnName("people_puts_sticker_to_auction");

                    b.Property<int>("PeopleSendsStickerOneOrMoreTimes")
                        .HasColumnType("int")
                        .HasColumnName("people_sends_sticker_one_or_more_times");

                    b.Property<int>("RoulettePlayCount")
                        .HasColumnType("int")
                        .HasColumnName("roulette_play_count");

                    b.HasKey("Date")
                        .HasName("pk_count_logs");

                    b.ToTable("count_logs", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.DailyTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("progress");

                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_tasks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_daily_tasks_user_id");

                    b.ToTable("daily_tasks", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.InviteInfo", b =>
                {
                    b.Property<long>("id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("InviteKey")
                        .HasColumnType("longtext")
                        .HasColumnName("invite_key");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("invited_at");

                    b.Property<long?>("InvitedById")
                        .HasColumnType("bigint")
                        .HasColumnName("invited_by_id");

                    b.HasKey("id")
                        .HasName("pk_invite_info");

                    b.HasIndex("InvitedById")
                        .HasDatabaseName("ix_invite_info_invited_by_id");

                    b.ToTable("invite_info", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<long>("LevelExpGoal")
                        .HasColumnType("bigint")
                        .HasColumnName("level_exp_goal");

                    b.Property<string>("LevelReward")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("level_reward");

                    b.Property<int>("LevelValue")
                        .HasColumnType("int")
                        .HasColumnName("level_value");

                    b.HasKey("Id")
                        .HasName("pk_levels");

                    b.ToTable("levels", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Pack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("author");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("GifPreviewFileId")
                        .HasColumnType("longtext")
                        .HasColumnName("gif_preview_file_id");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_exclusive");

                    b.Property<bool?>("IsPreviewAnimated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_preview_animated");

                    b.Property<long>("OpenedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("opened_count");

                    b.Property<string>("PreviewFileId")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("preview_file_id");

                    b.Property<int>("PriceCoins")
                        .HasColumnType("int")
                        .HasColumnName("price_coins");

                    b.Property<int>("PriceGems")
                        .HasColumnType("int")
                        .HasColumnName("price_gems");

                    b.HasKey("Id")
                        .HasName("pk_packs");

                    b.ToTable("packs", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("InvoicePayload")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("invoice_payload");

                    b.Property<string>("ProviderPaymentChargeId")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("provider_payment_charge_id");

                    b.Property<string>("TelegramPaymentChargeId")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("telegram_payment_charge_id");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int")
                        .HasColumnName("total_amount");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payments_user_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.PuzzlePiece", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("file_id");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<int>("PieceCount")
                        .HasColumnType("int")
                        .HasColumnName("piece_count");

                    b.Property<long>("StickerId")
                        .HasColumnType("bigint")
                        .HasColumnName("sticker_id");

                    b.HasKey("Id")
                        .HasName("pk_puzzle_pieces");

                    b.HasIndex("StickerId")
                        .HasDatabaseName("ix_puzzle_pieces_sticker_id");

                    b.ToTable("puzzle_pieces", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.SpecialOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalPrize")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("additional_prize");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<int>("Discount")
                        .HasColumnType("int")
                        .HasColumnName("discount");

                    b.Property<bool>("IsInfinite")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_infinite");

                    b.Property<bool?>("IsPreviewAnimated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_preview_animated");

                    b.Property<int>("PackId")
                        .HasColumnType("int")
                        .HasColumnName("pack_id");

                    b.Property<string>("PreviewFileId")
                        .HasColumnType("longtext")
                        .HasColumnName("preview_file_id");

                    b.Property<int>("PriceCoins")
                        .HasColumnType("int")
                        .HasColumnName("price_coins");

                    b.Property<int>("PriceGems")
                        .HasColumnType("int")
                        .HasColumnName("price_gems");

                    b.Property<DateTime?>("TimeLimit")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time_limit");

                    b.Property<bool>("TimeLimited")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("time_limited");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_special_orders");

                    b.HasIndex("PackId")
                        .HasDatabaseName("ix_special_orders_pack_id");

                    b.ToTable("special_orders", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.SpecialOrderUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_special_order_users");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_special_order_users_order_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_special_order_users_user_id");

                    b.ToTable("special_order_users", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Sticker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("author");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("description");

                    b.Property<int>("Effect")
                        .HasColumnType("int")
                        .HasColumnName("effect");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("emoji");

                    b.Property<int>("ExclusiveTask")
                        .HasColumnType("int")
                        .HasColumnName("exclusive_task");

                    b.Property<int>("ExclusiveTaskGoal")
                        .HasColumnType("int")
                        .HasColumnName("exclusive_task_goal");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("file_id");

                    b.Property<string>("ForSaleFileId")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("for_sale_file_id");

                    b.Property<string>("GrayFileId")
                        .HasMaxLength(127)
                        .HasColumnType("varchar(127)")
                        .HasColumnName("gray_file_id");

                    b.Property<int>("Income")
                        .HasColumnType("int")
                        .HasColumnName("income");

                    b.Property<int>("IncomeTime")
                        .HasColumnType("int")
                        .HasColumnName("income_time");

                    b.Property<int>("IncomeType")
                        .HasColumnType("int")
                        .HasColumnName("income_type");

                    b.Property<bool>("IsAnimated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_animated");

                    b.Property<bool?>("IsForSaleAnimated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_for_sale_animated");

                    b.Property<int>("PackId")
                        .HasColumnType("int")
                        .HasColumnName("pack_id");

                    b.Property<int>("Tier")
                        .HasColumnType("int")
                        .HasColumnName("tier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_stickers");

                    b.HasIndex("PackId")
                        .HasDatabaseName("ix_stickers_pack_id");

                    b.ToTable("stickers", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.TelegramChat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int>("ChatType")
                        .HasColumnType("int")
                        .HasColumnName("chat_type");

                    b.Property<bool>("DistributionsDisabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distributions_disabled");

                    b.Property<int>("GiveawayDuration")
                        .HasColumnType("int")
                        .HasColumnName("giveaway_duration");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_blocked");

                    b.Property<DateTime?>("LastGiveaway")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_giveaway");

                    b.Property<int>("MaxExpGain")
                        .HasColumnType("int")
                        .HasColumnName("max_exp_gain");

                    b.Property<int>("MembersCount")
                        .HasColumnType("int")
                        .HasColumnName("members_count");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_telegram_chats");

                    b.ToTable("telegram_chats", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("blocked_at");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<bool>("FirstReward")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("first_reward");

                    b.Property<long?>("InviteInfoid")
                        .HasColumnType("bigint")
                        .HasColumnName("invite_infoid");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_blocked");

                    b.Property<int>("PrivilegeLevel")
                        .HasColumnType("int")
                        .HasColumnName("privilege_level");

                    b.Property<DateTime>("UnblockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("unblocked_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("InviteInfoid")
                        .HasDatabaseName("ix_users_invite_infoid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.UserActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("longtext")
                        .HasColumnName("additional_data");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_activities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_activities_user_id");

                    b.ToTable("user_activities", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.UserPacks", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<int>("PackId")
                        .HasColumnType("int")
                        .HasColumnName("pack_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_packs");

                    b.HasIndex("PackId")
                        .HasDatabaseName("ix_user_packs_pack_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_packs_user_id");

                    b.ToTable("user_packs", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.UserSticker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("ChatRouletteId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_roulette_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<int>("ExclusiveTaskProgress")
                        .HasColumnType("int")
                        .HasColumnName("exclusive_task_progress");

                    b.Property<DateTime>("GivePrizeDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("give_prize_date");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_unlocked");

                    b.Property<DateTime>("LastUsage")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_usage");

                    b.Property<DateTime>("Payout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payout");

                    b.Property<long>("StickerId")
                        .HasColumnType("bigint")
                        .HasColumnName("sticker_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_stickers");

                    b.HasIndex("ChatRouletteId")
                        .HasDatabaseName("ix_user_stickers_chat_roulette_id");

                    b.HasIndex("StickerId")
                        .HasDatabaseName("ix_user_stickers_sticker_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_stickers_user_id");

                    b.ToTable("user_stickers", (string)null);
                });

            modelBuilder.Entity("ChannelGiveawayUser", b =>
                {
                    b.Property<long>("AwardedUsersId")
                        .HasColumnType("bigint")
                        .HasColumnName("awarded_users_id");

                    b.Property<int>("UsedGiveawaysId")
                        .HasColumnType("int")
                        .HasColumnName("used_giveaways_id");

                    b.HasKey("AwardedUsersId", "UsedGiveawaysId")
                        .HasName("pk_channel_giveaway_user");

                    b.HasIndex("UsedGiveawaysId")
                        .HasDatabaseName("ix_channel_giveaway_user_used_giveaways_id");

                    b.ToTable("channel_giveaway_user", (string)null);
                });

            modelBuilder.Entity("TelegramChatUser", b =>
                {
                    b.Property<long>("AvailableChatsId")
                        .HasColumnType("bigint")
                        .HasColumnName("available_chats_id");

                    b.Property<long>("MembersId")
                        .HasColumnType("bigint")
                        .HasColumnName("members_id");

                    b.HasKey("AvailableChatsId", "MembersId")
                        .HasName("pk_telegram_chat_user");

                    b.HasIndex("MembersId")
                        .HasDatabaseName("ix_telegram_chat_user_members_id");

                    b.ToTable("telegram_chat_user", (string)null);
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Auction", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.Sticker", "Sticker")
                        .WithMany()
                        .HasForeignKey("StickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_stickers_sticker_id");

                    b.HasOne("CardCollector.Database.Entity.User", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_users_trader_id");

                    b.Navigation("Sticker");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.ChannelGiveaway", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.TelegramChat", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .HasConstraintName("fk_channel_giveaways_telegram_chats_channel_id");

                    b.HasOne("CardCollector.Database.Entity.Sticker", "SelectedSticker")
                        .WithMany()
                        .HasForeignKey("SelectedStickerId")
                        .HasConstraintName("fk_channel_giveaways_stickers_selected_sticker_id");

                    b.Navigation("Channel");

                    b.Navigation("SelectedSticker");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.ChatRoulette", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_roulette_users_creator_id");

                    b.HasOne("CardCollector.Database.Entity.TelegramChat", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_roulette_telegram_chats_group_id");

                    b.Navigation("Creator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.DailyTask", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.User", "User")
                        .WithMany("DailyTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_tasks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.InviteInfo", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .HasConstraintName("fk_invite_info_users_invited_by_id");

                    b.HasOne("CardCollector.Database.Entity.User", "User")
                        .WithOne("InviteInfo")
                        .HasForeignKey("CardCollector.Database.Entity.InviteInfo", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invite_info_users_id");

                    b.OwnsOne("CardCollector.Database.Entity.BeginnersTasksProgress", "TasksProgress", b1 =>
                        {
                            b1.Property<long>("InviteInfoid")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<bool>("BuyStandardPack")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("buy_standard_pack");

                            b1.Property<bool>("BuyStickerOnAuction")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("buy_sticker_on_auction");

                            b1.Property<int>("CollectIncome")
                                .HasColumnType("int")
                                .HasColumnName("collect_income");

                            b1.Property<bool>("CombineStickers")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("combine_stickers");

                            b1.Property<bool>("Donate")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("donate");

                            b1.Property<bool>("InviteFriend")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("invite_friend");

                            b1.Property<bool>("OpenPack")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("open_pack");

                            b1.Property<bool>("PlaceStickerOnAuction")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("place_sticker_on_auction");

                            b1.Property<int>("PlayRoulette")
                                .HasColumnType("int")
                                .HasColumnName("play_roulette");

                            b1.Property<int>("Progress")
                                .HasColumnType("int")
                                .HasColumnName("progress");

                            b1.Property<int>("SendStickersToPrivate")
                                .HasColumnType("int")
                                .HasColumnName("send_stickers_to_private");

                            b1.Property<bool>("TakePartAtChatGiveaway")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("take_part_at_chat_giveaway");

                            b1.Property<int>("WinRoulette")
                                .HasColumnType("int")
                                .HasColumnName("win_roulette");

                            b1.HasKey("InviteInfoid")
                                .HasName("pk_beginners_tasks_progress");

                            b1.ToTable("beginners_tasks_progress", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InviteInfoid")
                                .HasConstraintName("fk_beginners_tasks_progress_invite_info_id");
                        });

                    b.Navigation("InvitedBy");

                    b.Navigation("TasksProgress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Payment", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.PuzzlePiece", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.Sticker", "Sticker")
                        .WithMany("PuzzlePieces")
                        .HasForeignKey("StickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_puzzle_pieces_stickers_sticker_id");

                    b.Navigation("Sticker");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.SpecialOrder", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.Pack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_special_orders_packs_pack_id");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.SpecialOrderUser", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.SpecialOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_special_order_users_special_orders_order_id");

                    b.HasOne("CardCollector.Database.Entity.User", "User")
                        .WithMany("SpecialOrdersUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_special_order_users_users_user_id");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Sticker", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.Pack", "Pack")
                        .WithMany("Stickers")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stickers_packs_pack_id");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.User", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.InviteInfo", null)
                        .WithMany("InvitedFriends")
                        .HasForeignKey("InviteInfoid")
                        .HasConstraintName("fk_users_invite_info_invite_infoid");

                    b.OwnsOne("CardCollector.Database.Entity.Cash", "Cash", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<int>("Candies")
                                .HasColumnType("int")
                                .HasColumnName("candies");

                            b1.Property<int>("Coins")
                                .HasColumnType("int")
                                .HasColumnName("coins");

                            b1.Property<int>("Gems")
                                .HasColumnType("int")
                                .HasColumnName("gems");

                            b1.Property<DateTime>("LastPayout")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("last_payout");

                            b1.Property<int>("MaxCapacity")
                                .HasColumnType("int")
                                .HasColumnName("max_capacity");

                            b1.HasKey("UserId")
                                .HasName("pk_user_cash");

                            b1.ToTable("user_cash", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_cash_users_id");
                        });

                    b.OwnsOne("CardCollector.Database.Entity.UserLevel", "Level", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("CurrentExp")
                                .HasColumnType("bigint")
                                .HasColumnName("current_exp");

                            b1.Property<int>("Level")
                                .HasColumnType("int")
                                .HasColumnName("level");

                            b1.Property<long>("TotalExp")
                                .HasColumnType("bigint")
                                .HasColumnName("total_exp");

                            b1.HasKey("UserId")
                                .HasName("pk_user_level");

                            b1.ToTable("user_level", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_level_users_id");
                        });

                    b.OwnsOne("CardCollector.Database.Entity.UserMessages", "Messages", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("ChatMessages")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("chat_messages");

                            b1.Property<string>("ChatStickers")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("chat_stickers");

                            b1.Property<int>("CollectIncomeMessageId")
                                .HasColumnType("int")
                                .HasColumnName("collect_income_message_id");

                            b1.Property<int>("DailyTaskAlertMessageId")
                                .HasColumnType("int")
                                .HasColumnName("daily_task_alert_message_id");

                            b1.Property<int>("DailyTaskMessageId")
                                .HasColumnType("int")
                                .HasColumnName("daily_task_message_id");

                            b1.Property<int>("DailyTaskProgressMessageId")
                                .HasColumnType("int")
                                .HasColumnName("daily_task_progress_message_id");

                            b1.Property<int>("MenuMessageId")
                                .HasColumnType("int")
                                .HasColumnName("menu_message_id");

                            b1.Property<int>("TopUsersMessageId")
                                .HasColumnType("int")
                                .HasColumnName("top_users_message_id");

                            b1.HasKey("UserId")
                                .HasName("pk_user_messages");

                            b1.ToTable("user_messages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_messages_users_id");
                        });

                    b.OwnsOne("CardCollector.Database.Entity.UserSettings", "Settings", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Settings")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("settings");

                            b1.HasKey("UserId")
                                .HasName("pk_user_settings");

                            b1.ToTable("user_settings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_settings_users_id");
                        });

                    b.Navigation("Cash")
                        .IsRequired();

                    b.Navigation("Level")
                        .IsRequired();

                    b.Navigation("Messages")
                        .IsRequired();

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("CardCollector.Database.Entity.UserActivity", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_activities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.UserPacks", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.Pack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_packs_packs_pack_id");

                    b.HasOne("CardCollector.Database.Entity.User", "User")
                        .WithMany("Packs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_packs_users_user_id");

                    b.Navigation("Pack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.UserSticker", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.ChatRoulette", null)
                        .WithMany("Bets")
                        .HasForeignKey("ChatRouletteId")
                        .HasConstraintName("fk_user_stickers_chat_roulette_chat_roulette_id");

                    b.HasOne("CardCollector.Database.Entity.Sticker", "Sticker")
                        .WithMany()
                        .HasForeignKey("StickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_stickers_stickers_sticker_id");

                    b.HasOne("CardCollector.Database.Entity.User", "User")
                        .WithMany("Stickers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_stickers_users_user_id");

                    b.Navigation("Sticker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChannelGiveawayUser", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("AwardedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_giveaway_user_users_awarded_users_id");

                    b.HasOne("CardCollector.Database.Entity.ChannelGiveaway", null)
                        .WithMany()
                        .HasForeignKey("UsedGiveawaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_giveaway_user_channel_giveaways_used_giveaways_id");
                });

            modelBuilder.Entity("TelegramChatUser", b =>
                {
                    b.HasOne("CardCollector.Database.Entity.TelegramChat", null)
                        .WithMany()
                        .HasForeignKey("AvailableChatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_chat_user_telegram_chats_available_chats_id");

                    b.HasOne("CardCollector.Database.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_chat_user_users_members_id");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.ChatRoulette", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.InviteInfo", b =>
                {
                    b.Navigation("InvitedFriends");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Pack", b =>
                {
                    b.Navigation("Stickers");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.Sticker", b =>
                {
                    b.Navigation("PuzzlePieces");
                });

            modelBuilder.Entity("CardCollector.Database.Entity.User", b =>
                {
                    b.Navigation("DailyTasks");

                    b.Navigation("InviteInfo");

                    b.Navigation("Packs");

                    b.Navigation("SpecialOrdersUser");

                    b.Navigation("Stickers");
                });
#pragma warning restore 612, 618
        }
    }
}
