//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CallbackQueryCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CallbackQueryCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.CallbackQueryCommands", typeof(CallbackQueryCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author.
        /// </summary>
        internal static string author_callback {
            get {
                return ResourceManager.GetString("author_callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change_page.
        /// </summary>
        internal static string change_page {
            get {
                return ResourceManager.GetString("change_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собрать прибыль.
        /// </summary>
        internal static string collect_income {
            get {
                return ResourceManager.GetString("collect_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмоция.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emoji.
        /// </summary>
        internal static string emoji_callback {
            get {
                return ResourceManager.GetString("emoji_callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to →.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать стикеры.
        /// </summary>
        internal static string show_stickers {
            get {
                return ResourceManager.GetString("show_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        internal static string sorting {
            get {
                return ResourceManager.GetString("sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorting.
        /// </summary>
        internal static string sorting_callback {
            get {
                return ResourceManager.GetString("sorting_callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тир.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tier.
        /// </summary>
        internal static string tier_callback {
            get {
                return ResourceManager.GetString("tier_callback", resourceCulture);
            }
        }
    }
}
