//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Command {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Command() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.Command", typeof(Command).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        internal static string buy_sticker {
            get {
                return ResourceManager.GetString("buy_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string clear_chat {
            get {
                return ResourceManager.GetString("clear_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collect_income.
        /// </summary>
        internal static string collect_income {
            get {
                return ResourceManager.GetString("collect_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to combine.
        /// </summary>
        internal static string combine {
            get {
                return ResourceManager.GetString("combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emoji.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price_coins_from.
        /// </summary>
        internal static string price_coins_from {
            get {
                return ResourceManager.GetString("price_coins_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price_coins_to.
        /// </summary>
        internal static string price_coins_to {
            get {
                return ResourceManager.GetString("price_coins_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price_gems_from.
        /// </summary>
        internal static string price_gems_from {
            get {
                return ResourceManager.GetString("price_gems_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price_gems_to.
        /// </summary>
        internal static string price_gems_to {
            get {
                return ResourceManager.GetString("price_gems_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        internal static string select_sticker {
            get {
                return ResourceManager.GetString("select_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sell.
        /// </summary>
        internal static string sell_on_auction {
            get {
                return ResourceManager.GetString("sell_on_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        internal static string send_sticker {
            get {
                return ResourceManager.GetString("send_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tier.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlim.
        /// </summary>
        internal static string unlimited_stickers {
            get {
                return ResourceManager.GetString("unlimited_stickers", resourceCulture);
            }
        }
    }
}
