//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (все).
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены?.
        /// </summary>
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор:.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пак художника.
        /// </summary>
        internal static string author_packs {
            get {
                return ResourceManager.GetString("author_packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бот уходит на технический перерыв....
        /// </summary>
        internal static string bot_turning_off {
            get {
                return ResourceManager.GetString("bot_turning_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно изменить количество!.
        /// </summary>
        internal static string cant_change_count {
            get {
                return ResourceManager.GetString("cant_change_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить стикеры. Необходимое количество уже собрано..
        /// </summary>
        internal static string cant_combine {
            get {
                return ResourceManager.GetString("cant_combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно уменьшить количество стикеров!.
        /// </summary>
        internal static string cant_decrease {
            get {
                return ResourceManager.GetString("cant_decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно увеличить количество стикеров!.
        /// </summary>
        internal static string cant_increase {
            get {
                return ResourceManager.GetString("cant_increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите автора из списка ниже:.
        /// </summary>
        internal static string choose_author {
            get {
                return ResourceManager.GetString("choose_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите одну из опций ниже.
        /// </summary>
        internal static string choose_option {
            get {
                return ResourceManager.GetString("choose_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите диапазон цен из списка ниже:.
        /// </summary>
        internal static string choose_price {
            get {
                return ResourceManager.GetString("choose_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сортировку из списка ниже:.
        /// </summary>
        internal static string choose_sort {
            get {
                return ResourceManager.GetString("choose_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тир из списка ниже:.
        /// </summary>
        internal static string choose_tier {
            get {
                return ResourceManager.GetString("choose_tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монеты.
        /// </summary>
        internal static string coins {
            get {
                return ResourceManager.GetString("coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить все стикеры. Было добавлено только.
        /// </summary>
        internal static string combine_added_only {
            get {
                return ResourceManager.GetString("combine_added_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили стикер.
        /// </summary>
        internal static string combined_sticker {
            get {
                return ResourceManager.GetString("combined_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! На аукционе действует комиссия в размере 30%..
        /// </summary>
        internal static string comission_warning {
            get {
                return ResourceManager.GetString("comission_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите покупку:.
        /// </summary>
        internal static string confirm_buying {
            get {
                return ResourceManager.GetString("confirm_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите выставление.
        /// </summary>
        internal static string confirm_selling {
            get {
                return ResourceManager.GetString("confirm_selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили стикер:.
        /// </summary>
        internal static string congratulation {
            get {
                return ResourceManager.GetString("congratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие примененные фильтры:.
        /// </summary>
        internal static string current_filters {
            get {
                return ResourceManager.GetString("current_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая стоимость.
        /// </summary>
        internal static string current_price {
            get {
                return ResourceManager.GetString("current_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не забывайте заходить и выполнять ежедневные задания. Список ежедневных заданий вы можете посмотреть в профиле. Хорошего дня и приятного пользования нашим ботом!.
        /// </summary>
        internal static string daily_task_alertation {
            get {
                return ResourceManager.GetString("daily_task_alertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаляю файлы....
        /// </summary>
        internal static string deleting_files {
            get {
                return ResourceManager.GetString("deleting_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаю файл....
        /// </summary>
        internal static string downloading_file {
            get {
                return ResourceManager.GetString("downloading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмоция:.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите эмоцию.
        /// </summary>
        internal static string enter_emoji {
            get {
                return ResourceManager.GetString("enter_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите только одну эмоцию!.
        /// </summary>
        internal static string enter_only_one_emoji {
            get {
                return ResourceManager.GetString("enter_only_one_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вашу стоимость в монетах.
        /// </summary>
        internal static string enter_your_coins_price {
            get {
                return ResourceManager.GetString("enter_your_coins_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вашу стоимость в алмазах (за 1шт).
        /// </summary>
        internal static string enter_your_gems_price {
            get {
                return ResourceManager.GetString("enter_your_gems_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алмазы.
        /// </summary>
        internal static string gems {
            get {
                return ResourceManager.GetString("gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименьшая цена:.
        /// </summary>
        internal static string lower_price {
            get {
                return ResourceManager.GetString("lower_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете выбрать одну из опций ниже.
        /// </summary>
        internal static string menu_message {
            get {
                return ResourceManager.GetString("menu_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно монет!.
        /// </summary>
        internal static string not_enougth_coins {
            get {
                return ResourceManager.GetString("not_enougth_coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно алмазов!.
        /// </summary>
        internal static string not_enougth_gems {
            get {
                return ResourceManager.GetString("not_enougth_gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно стикеров в магазине!.
        /// </summary>
        internal static string not_enougth_stickers {
            get {
                return ResourceManager.GetString("not_enougth_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время акции истекло!.
        /// </summary>
        internal static string offer_expired {
            get {
                return ResourceManager.GetString("offer_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При покупке &quot;Случайного пака&quot; Вам может выпасть ЛЮБОЙ стикер от ЛЮБОГО художника
        ///
        ///При покупке &quot;Пака художника&quot; Вам может выпасть ЛЮБОЙ стикер от выбранного Вами художника художника
        ///
        ///Вероятности выпадения стикера с тиром:
        ///1 - 80%
        ///2 - 16%
        ///3 - 3.3%
        ///4 - 0.7%.
        /// </summary>
        internal static string pack_info {
            get {
                return ResourceManager.GetString("pack_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили случайный пак! Открыть его можно во вкладке профиля..
        /// </summary>
        internal static string pack_prize {
            get {
                return ResourceManager.GetString("pack_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно паков.
        /// </summary>
        internal static string packs_count_zero {
            get {
                return ResourceManager.GetString("packs_count_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        internal static string page_not_found {
            get {
                return ResourceManager.GetString("page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите только эмоцию.
        /// </summary>
        internal static string please_enter_emoji {
            get {
                return ResourceManager.GetString("please_enter_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите положительное целое число.
        /// </summary>
        internal static string please_enter_price {
            get {
                return ResourceManager.GetString("please_enter_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость:.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайный пак.
        /// </summary>
        internal static string random_packs {
            get {
                return ResourceManager.GetString("random_packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читаю документ....
        /// </summary>
        internal static string reading_document {
            get {
                return ResourceManager.GetString("reading_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установите фильтры кнопками ниже:.
        /// </summary>
        internal static string select_filter {
            get {
                return ResourceManager.GetString("select_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите одну из опций ниже:.
        /// </summary>
        internal static string shop_message {
            get {
                return ResourceManager.GetString("shop_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка:.
        /// </summary>
        internal static string sorting {
            get {
                return ResourceManager.GetString("sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторских паков:.
        /// </summary>
        internal static string specific_packs {
            get {
                return ResourceManager.GetString("specific_packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать! Этот бот позволяет вам коллекционировать стикеры. Вы можете выбрать одну из опций ниже. Напишите /help, чтобы получить подробную справку..
        /// </summary>
        internal static string start_message {
            get {
                return ResourceManager.GetString("start_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стикеры будут обновлены через 15 минут.
        /// </summary>
        internal static string stickers_will_be_updated {
            get {
                return ResourceManager.GetString("stickers_will_be_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товар успешно попал на аукцион.
        /// </summary>
        internal static string successfully_selling {
            get {
                return ResourceManager.GetString("successfully_selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за покупку!.
        /// </summary>
        internal static string thanks_for_buying {
            get {
                return ResourceManager.GetString("thanks_for_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тир:.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несобранная прибыль.
        /// </summary>
        internal static string uncllected_income {
            get {
                return ResourceManager.GetString("uncllected_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неожиданная ошибка, попробуйте еще раз..
        /// </summary>
        internal static string unexpected_exception {
            get {
                return ResourceManager.GetString("unexpected_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковываю архив.....
        /// </summary>
        internal static string unzipping_file {
            get {
                return ResourceManager.GetString("unzipping_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите архив со стикерами и таблицей в формате zip.
        /// </summary>
        internal static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже воспользовались данным предложением!.
        /// </summary>
        internal static string you_already_use_this_offer {
            get {
                return ResourceManager.GetString("you_already_use_this_offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено.
        /// </summary>
        internal static string you_collected {
            get {
                return ResourceManager.GetString("you_collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы продали.
        /// </summary>
        internal static string you_sold {
            get {
                return ResourceManager.GetString("you_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        internal static string your_cash {
            get {
                return ResourceManager.GetString("your_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши ежедневные задания:.
        /// </summary>
        internal static string your_daily_tasks {
            get {
                return ResourceManager.GetString("your_daily_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас сейчас:.
        /// </summary>
        internal static string your_packs {
            get {
                return ResourceManager.GetString("your_packs", resourceCulture);
            }
        }
    }
}
