//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стикер с вотеркой добавлен успешно!.
        /// </summary>
        internal static string add_watermark_success {
            get {
                return ResourceManager.GetString("add_watermark_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔&lt;b&gt;Уведомления&lt;/b&gt;🔔.
        /// </summary>
        internal static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (все).
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены?.
        /// </summary>
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пак художника.
        /// </summary>
        internal static string author_pack {
            get {
                return ResourceManager.GetString("author_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список доступных специальных предложений:.
        /// </summary>
        internal static string available_offers {
            get {
                return ResourceManager.GetString("available_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бот уходит на технический перерыв....
        /// </summary>
        internal static string bot_turning_off {
            get {
                return ResourceManager.GetString("bot_turning_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка алмазов производится по курсу ₽69 = 100💎
        ///
        ///Выберите одну из опций ниже:.
        /// </summary>
        internal static string buy_gems {
            get {
                return ResourceManager.GetString("buy_gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно изменить количество!.
        /// </summary>
        internal static string cant_change_count {
            get {
                return ResourceManager.GetString("cant_change_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить стикеры. Необходимое количество уже собрано..
        /// </summary>
        internal static string cant_combine {
            get {
                return ResourceManager.GetString("cant_combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя продать товар за 0!.
        /// </summary>
        internal static string cant_sell_zero {
            get {
                return ResourceManager.GetString("cant_sell_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер копилки.
        /// </summary>
        internal static string cash_capacity {
            get {
                return ResourceManager.GetString("cash_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите автора из списка ниже:.
        /// </summary>
        internal static string choose_author {
            get {
                return ResourceManager.GetString("choose_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите желаемое количество монет:.
        /// </summary>
        internal static string choose_exchange_sum {
            get {
                return ResourceManager.GetString("choose_exchange_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите одну из опций ниже.
        /// </summary>
        internal static string choose_option {
            get {
                return ResourceManager.GetString("choose_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите диапазон цен из списка ниже:.
        /// </summary>
        internal static string choose_price {
            get {
                return ResourceManager.GetString("choose_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите платежную систему.
        /// </summary>
        internal static string choose_provider {
            get {
                return ResourceManager.GetString("choose_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сортировку из списка ниже:.
        /// </summary>
        internal static string choose_sort {
            get {
                return ResourceManager.GetString("choose_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите стикер:.
        /// </summary>
        internal static string choose_sticker {
            get {
                return ResourceManager.GetString("choose_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тир из списка ниже:.
        /// </summary>
        internal static string choose_tier {
            get {
                return ResourceManager.GetString("choose_tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пользователя.
        /// </summary>
        internal static string choose_user {
            get {
                return ResourceManager.GetString("choose_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монеты.
        /// </summary>
        internal static string coins {
            get {
                return ResourceManager.GetString("coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получите монет:.
        /// </summary>
        internal static string coins_exchange_count {
            get {
                return ResourceManager.GetString("coins_exchange_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить все стикеры. Было добавлено только.
        /// </summary>
        internal static string combine_added_only {
            get {
                return ResourceManager.GetString("combine_added_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили стикер.
        /// </summary>
        internal static string combined_sticker {
            get {
                return ResourceManager.GetString("combined_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! На аукционе действует комиссия в размере 30%..
        /// </summary>
        internal static string comission_warning {
            get {
                return ResourceManager.GetString("comission_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите покупку:.
        /// </summary>
        internal static string confirm_buying {
            get {
                return ResourceManager.GetString("confirm_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите обмен:.
        /// </summary>
        internal static string confirm_exchange {
            get {
                return ResourceManager.GetString("confirm_exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите свой вход на сайте.
        /// </summary>
        internal static string confirm_login {
            get {
                return ResourceManager.GetString("confirm_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите выставление за.
        /// </summary>
        internal static string confirm_selling {
            get {
                return ResourceManager.GetString("confirm_selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите остановку (повторите команду).
        /// </summary>
        internal static string confirm_stopping {
            get {
                return ResourceManager.GetString("confirm_stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили стикер:.
        /// </summary>
        internal static string congratulation {
            get {
                return ResourceManager.GetString("congratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы достигли уровня.
        /// </summary>
        internal static string congratulation_new_level {
            get {
                return ResourceManager.GetString("congratulation_new_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👑&lt;b&gt;Панель управления&lt;/b&gt;👑.
        /// </summary>
        internal static string control_panel {
            get {
                return ResourceManager.GetString("control_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество отправлений за этот день в беседу.
        /// </summary>
        internal static string count_sends_per_day {
            get {
                return ResourceManager.GetString("count_sends_per_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт.
        /// </summary>
        internal static string current_exp {
            get {
                return ResourceManager.GetString("current_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие примененные фильтры.
        /// </summary>
        internal static string current_filters {
            get {
                return ResourceManager.GetString("current_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая стоимость.
        /// </summary>
        internal static string current_price {
            get {
                return ResourceManager.GetString("current_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не забывайте заходить и выполнять ежедневные задания. Список ежедневных заданий вы можете посмотреть в профиле. Хорошего дня и приятного пользования нашим ботом!.
        /// </summary>
        internal static string daily_task_alertation {
            get {
                return ResourceManager.GetString("daily_task_alertation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и/или время уже истекли!.
        /// </summary>
        internal static string date_is_expired {
            get {
                return ResourceManager.GetString("date_is_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаляю файлы....
        /// </summary>
        internal static string deleting_files {
            get {
                return ResourceManager.GetString("deleting_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаю файл....
        /// </summary>
        internal static string downloading_file {
            get {
                return ResourceManager.GetString("downloading_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили +25% к своим алмазам!.
        /// </summary>
        internal static string effect_Diamonds25Percent {
            get {
                return ResourceManager.GetString("effect_Diamonds25Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Ваша копилка увеличена на 200!.
        /// </summary>
        internal static string effect_PiggyBank200 {
            get {
                return ResourceManager.GetString("effect_PiggyBank200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили паки в количестве.
        /// </summary>
        internal static string effect_Random1Pack5Day {
            get {
                return ResourceManager.GetString("effect_Random1Pack5Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили следующие стикеры:.
        /// </summary>
        internal static string effect_RandomSticker1Tier2Day {
            get {
                return ResourceManager.GetString("effect_RandomSticker1Tier2Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили следующие стикеры:.
        /// </summary>
        internal static string effect_RandomSticker2Tier3Day {
            get {
                return ResourceManager.GetString("effect_RandomSticker2Tier3Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмоция.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст кнопки. Пожалуйста, воздержитесь от слишком длинного текста, рекомендуемый объем 2-3 слова.
        ///
        ///Вы можете вставить в текст значения из раздачи, просто вставьте в текст следующие конструкции (не обязательно):
        ///&lt;code&gt;{0}&lt;/code&gt; - количество призов всего
        ///&lt;code&gt;{1}&lt;/code&gt; - название приза
        ///
        ///Вы можете пропустить этот шаг, в таком случае будет задано значение по умолчанию &quot;Забрать награду {0}&quot;.
        /// </summary>
        internal static string enter_button_text {
            get {
                return ResourceManager.GetString("enter_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите эмоцию.
        /// </summary>
        internal static string enter_emoji {
            get {
                return ResourceManager.GetString("enter_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите сообщение раздачи:
        ///
        ///Вы можете вставить в текст значения из раздачи, просто вставьте в текст следующие конструкции (не обязательно):
        ///&lt;code&gt;{0}&lt;/code&gt; - количество призов всего
        ///&lt;code&gt;{1}&lt;/code&gt; - название приза.
        /// </summary>
        internal static string enter_giveaway_message {
            get {
                return ResourceManager.GetString("enter_giveaway_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество призов:.
        /// </summary>
        internal static string enter_number_of_prizes {
            get {
                return ResourceManager.GetString("enter_number_of_prizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте дату и время, когда раздача должна быть отправлена в формате: dd.MM hh:mm
        ///dd - день
        ///MM - месяц
        ///hh - часы
        ///mm - минуты
        ///Вы можете пропустить этот шаг, тогда раздача будет отправлена сразу после подтверждения..
        /// </summary>
        internal static string enter_when_giveaway_will_be_sended {
            get {
                return ResourceManager.GetString("enter_when_giveaway_will_be_sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вашу стоимость в алмазах (за 1шт).
        /// </summary>
        internal static string enter_your_gems_price {
            get {
                return ResourceManager.GetString("enter_your_gems_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при подготовке раздачи: {0}.
        /// </summary>
        internal static string error_when_preparing_giveaway {
            get {
                return ResourceManager.GetString("error_when_preparing_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка монет производится за алмазы, 1💎 = 10💰..
        /// </summary>
        internal static string exchange_mesage {
            get {
                return ResourceManager.GetString("exchange_mesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию! Вы получили 7 паков, используйте эту кнопку, чтобы открыть их..
        /// </summary>
        internal static string first_reward {
            get {
                return ResourceManager.GetString("first_reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за покупку алмазов в магазине.
        /// </summary>
        internal static string for_buy_gems {
            get {
                return ResourceManager.GetString("for_buy_gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алмазы.
        /// </summary>
        internal static string gems {
            get {
                return ResourceManager.GetString("gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы заплатите алмазов:.
        /// </summary>
        internal static string gems_exchange_count {
            get {
                return ResourceManager.GetString("gems_exchange_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздача завершена!.
        /// </summary>
        internal static string gievaway_now_ended {
            get {
                return ResourceManager.GetString("gievaway_now_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздача успешно создана!
        ///Ссылка на раздачу &lt;a href=&quot;{0}&quot;&gt;тык&lt;/a&gt;.
        /// </summary>
        internal static string giveaway_successfully_created {
            get {
                return ResourceManager.GetString("giveaway_successfully_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробное руководство по использованию бота ниже:
        ///https://telegra.ph/help-11-04-4.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный формат! Введите дату в формате dd.MM hh:mm.
        /// </summary>
        internal static string incorrect_datetime_format {
            get {
                return ResourceManager.GetString("incorrect_datetime_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика за &lt;b&gt;{0}&lt;/b&gt;:.
        /// </summary>
        internal static string logs_on_date {
            get {
                return ResourceManager.GetString("logs_on_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименьшая цена:.
        /// </summary>
        internal static string lower_price {
            get {
                return ResourceManager.GetString("lower_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⬇️&lt;b&gt;Главное меню&lt;/b&gt;⬇️.
        /// </summary>
        internal static string main_menu {
            get {
                return ResourceManager.GetString("main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно монет!.
        /// </summary>
        internal static string not_enougth_coins {
            get {
                return ResourceManager.GetString("not_enougth_coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно алмазов!.
        /// </summary>
        internal static string not_enougth_gems {
            get {
                return ResourceManager.GetString("not_enougth_gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно стикеров в магазине!.
        /// </summary>
        internal static string not_enougth_stickers {
            get {
                return ResourceManager.GetString("not_enougth_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет доступных специальных предложений! Возвращайтесь позже..
        /// </summary>
        internal static string offers_not_found {
            get {
                return ResourceManager.GetString("offers_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или введите другую сумму:.
        /// </summary>
        internal static string or_enter_another_sum {
            get {
                return ResourceManager.GetString("or_enter_another_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время акции истекло!.
        /// </summary>
        internal static string order_expired {
            get {
                return ResourceManager.GetString("order_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При покупке &quot;Случайного пака&quot; Вам может выпасть ЛЮБОЙ стикер от ЛЮБОГО художника
        ///
        ///При покупке &quot;Пака художника&quot; Вам может выпасть ЛЮБОЙ стикер от выбранного Вами художника
        ///
        ///Вероятности выпадения стикера с тиром:
        ///1 - 80%
        ///2 - 16%
        ///3 - 3.3%
        ///4 - 0.7%.
        /// </summary>
        internal static string pack_info {
            get {
                return ResourceManager.GetString("pack_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Вы получили обычный пак! Открыть его можно во вкладке профиля..
        /// </summary>
        internal static string pack_prize {
            get {
                return ResourceManager.GetString("pack_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет паков.
        /// </summary>
        internal static string packs_count_zero {
            get {
                return ResourceManager.GetString("packs_count_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница не найдена.
        /// </summary>
        internal static string page_not_found {
            get {
                return ResourceManager.GetString("page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подтвердите создание раздачи:.
        /// </summary>
        internal static string please_confirm_this_giveaway {
            get {
                return ResourceManager.GetString("please_confirm_this_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите только эмоцию.
        /// </summary>
        internal static string please_enter_emoji {
            get {
                return ResourceManager.GetString("please_enter_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите положительное целое число.
        /// </summary>
        internal static string please_enter_integer {
            get {
                return ResourceManager.GetString("please_enter_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, загрузите превью стикерпака.
        /// </summary>
        internal static string please_upload_preview {
            get {
                return ResourceManager.GetString("please_upload_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество призов должно быть положительным!.
        /// </summary>
        internal static string prize_count_must_be_positive {
            get {
                return ResourceManager.GetString("prize_count_must_be_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычный пак.
        /// </summary>
        internal static string random_packs {
            get {
                return ResourceManager.GetString("random_packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читаю документ....
        /// </summary>
        internal static string reading_document {
            get {
                return ResourceManager.GetString("reading_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши стикеры можно посмотреть, нажав на Коллекция..
        /// </summary>
        internal static string see_your_stickers {
            get {
                return ResourceManager.GetString("see_your_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите канал из предложенных ниже:.
        /// </summary>
        internal static string select_channel {
            get {
                return ResourceManager.GetString("select_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установите фильтры кнопками ниже.
        /// </summary>
        internal static string select_filter {
            get {
                return ResourceManager.GetString("select_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пак:.
        /// </summary>
        internal static string select_pack {
            get {
                return ResourceManager.GetString("select_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите стикер.
        /// </summary>
        internal static string select_sticker {
            get {
                return ResourceManager.GetString("select_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный чат заблокирован!.
        /// </summary>
        internal static string selected_chat_is_blocked {
            get {
                return ResourceManager.GetString("selected_chat_is_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправьте мне изображение для раздачи.
        ///Вы можете пропустить этот шаг..
        /// </summary>
        internal static string send_giveaway_image {
            get {
                return ResourceManager.GetString("send_giveaway_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за отправку стикера в беседу..
        /// </summary>
        internal static string send_sticker {
            get {
                return ResourceManager.GetString("send_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Отправка стикеров в личные сообщения&quot; прогресс.
        /// </summary>
        internal static string send_sticker_progress {
            get {
                return ResourceManager.GetString("send_sticker_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обложка успешно установлена.
        /// </summary>
        internal static string set_preview_success {
            get {
                return ResourceManager.GetString("set_preview_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙&lt;b&gt;Настройки&lt;/b&gt;⚙.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💎&lt;b&gt;Магазин&lt;/b&gt;💎.
        /// </summary>
        internal static string shop_message {
            get {
                return ResourceManager.GetString("shop_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        internal static string sorting {
            get {
                return ResourceManager.GetString("sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать! Этот бот позволяет вам коллекционировать стикеры. Вы можете выбрать одну из опций ниже.
        ///
        ///Чтобы получить начальные стикеры Вам нужно открыть:
        ///
        ///Магазин
        ///⬇
        ///Специальные предложения
        ///⬇
        ///3 стартовых пака бесплатно
        ///⬇
        ///0 💰
        ///
        ///Открыть свои наборы:
        ///
        ///Профиль
        ///⬇
        ///Мои паки
        ///⬇
        ///Открыть обычный пак
        ///
        ///Подробная инструкция и 🎁 доступны на нашем сайте: wyrmstore.com
        ///
        ///Руководство пользования: /help.
        /// </summary>
        internal static string start_message {
            get {
                return ResourceManager.GetString("start_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стикеры успешно загружены!.
        /// </summary>
        internal static string stickers_succesfully_uploaded {
            get {
                return ResourceManager.GetString("stickers_succesfully_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно авторизованы на сайте!.
        /// </summary>
        internal static string successfully_authorized {
            get {
                return ResourceManager.GetString("successfully_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно вернули {0} стикеров {1} с аукциона!.
        /// </summary>
        internal static string successfully_returned {
            get {
                return ResourceManager.GetString("successfully_returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товар успешно попал на аукцион.
        /// </summary>
        internal static string successfully_selling {
            get {
                return ResourceManager.GetString("successfully_selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за покупку! У вас в наличии:.
        /// </summary>
        internal static string thanks_for_buying {
            get {
                return ResourceManager.GetString("thanks_for_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за покупку алмазов!.
        /// </summary>
        internal static string thanks_for_buying_gems {
            get {
                return ResourceManager.GetString("thanks_for_buying_gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: спасибо, что купил у меня стикер!.
        /// </summary>
        internal static string thanks_for_buying_sticker {
            get {
                return ResourceManager.GetString("thanks_for_buying_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: спасибо, что продал мне стикер {1} в количестве {2}, вот твоя оплата {3}💎.
        /// </summary>
        internal static string thanks_for_selling_sticker {
            get {
                return ResourceManager.GetString("thanks_for_selling_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тир.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не забывайте собирать прибыль во вкладке профиля. Несобранная прибыль составляет.
        /// </summary>
        internal static string uncollected_income {
            get {
                return ResourceManager.GetString("uncollected_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла неожиданная ошибка, сообщите об этом разработчикам..
        /// </summary>
        internal static string unexpected_exception {
            get {
                return ResourceManager.GetString("unexpected_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление обложки успешно!.
        /// </summary>
        internal static string update_preview_success {
            get {
                return ResourceManager.GetString("update_preview_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стикер заменен успешно!.
        /// </summary>
        internal static string update_sticker_success {
            get {
                return ResourceManager.GetString("update_sticker_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите файл с вотермаркой для этого стикера:.
        /// </summary>
        internal static string upload_file_with_watermark {
            get {
                return ResourceManager.GetString("upload_file_with_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите новый файл.
        /// </summary>
        internal static string upload_new_file {
            get {
                return ResourceManager.GetString("upload_new_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, загрузите ваш xlsx файл с описанием стикеров, по одной строке на стикер. Соблюдайте порядок, в котором вы загружали стикеры.
        ///Структура таблицы должна сожержать столбцы в следующем порядке: Название, Автор, Тир, Эмоции, Эффект, Описание.
        ///Оставьте первую строку пустой или заполните ее этими заголовками, значения начинайте вписывать со !второй! строки.
        ///Поле &quot;Эффект&quot; Может содержать целочисленное значение. Вот описания этих значений:
        ///0 - Нет эффекта
        ///1 - Увеличивает копилку на 200 монет
        ///2 - Пол [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string upload_your_file {
            get {
                return ResourceManager.GetString("upload_your_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузите свои стикеры в формате .webp или .tgs в том порядке, в котором вы описываете их в таблице Excel. Когда завершите загрузку, нажмите на &quot;Завершить загрузку стикеров&quot;.
        /// </summary>
        internal static string upload_your_stickers {
            get {
                return ResourceManager.GetString("upload_your_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество загруженных стикеров:.
        /// </summary>
        internal static string uploaded_count {
            get {
                return ResourceManager.GetString("uploaded_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаю стикеры....
        /// </summary>
        internal static string uploading_stickers {
            get {
                return ResourceManager.GetString("uploading_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧪&lt;b&gt;Топ пользователей по опыту&lt;/b&gt;🧪.
        /// </summary>
        internal static string users_top_exp {
            get {
                return ResourceManager.GetString("users_top_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭐&lt;b&gt;Топ пользователей по количеству 4⭐ стикеров&lt;/b&gt;⭐.
        /// </summary>
        internal static string users_top_tier_4_stickers_count {
            get {
                return ResourceManager.GetString("users_top_tier_4_stickers_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже воспользовались данным предложением!.
        /// </summary>
        internal static string you_already_use_this_order {
            get {
                return ResourceManager.GetString("you_already_use_this_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже получили награду из этой раздачи..
        /// </summary>
        internal static string you_are_now_awarded {
            get {
                return ResourceManager.GetString("you_are_now_awarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы увеличить получаемый опыт, Вы можете добавить бота в беседу..
        /// </summary>
        internal static string you_can_add_bot_to_conversation {
            get {
                return ResourceManager.GetString("you_can_add_bot_to_conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено прибыли со стикеров:.
        /// </summary>
        internal static string you_collected {
            get {
                return ResourceManager.GetString("you_collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили.
        /// </summary>
        internal static string you_gained {
            get {
                return ResourceManager.GetString("you_gained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили.
        /// </summary>
        internal static string you_got {
            get {
                return ResourceManager.GetString("you_got", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы получили {0} с этой раздачи.
        /// </summary>
        internal static string you_got_from_this_giveaway {
            get {
                return ResourceManager.GetString("you_got_from_this_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        internal static string your_cash {
            get {
                return ResourceManager.GetString("your_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши ежедневные задания:.
        /// </summary>
        internal static string your_daily_tasks {
            get {
                return ResourceManager.GetString("your_daily_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша ссылка для входа.
        /// </summary>
        internal static string your_login_link {
            get {
                return ResourceManager.GetString("your_login_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас сейчас:.
        /// </summary>
        internal static string your_packs {
            get {
                return ResourceManager.GetString("your_packs", resourceCulture);
            }
        }
    }
}
