//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (все).
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор:.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите автора из списка ниже:.
        /// </summary>
        internal static string choose_author {
            get {
                return ResourceManager.GetString("choose_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите диапазон цен из списка ниже:.
        /// </summary>
        internal static string choose_price {
            get {
                return ResourceManager.GetString("choose_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сортировку из списка ниже:.
        /// </summary>
        internal static string choose_sort {
            get {
                return ResourceManager.GetString("choose_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тир из списка ниже:.
        /// </summary>
        internal static string choose_tier {
            get {
                return ResourceManager.GetString("choose_tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие примененные фильтры:.
        /// </summary>
        internal static string current_filters {
            get {
                return ResourceManager.GetString("current_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмоция:.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите эмоцию.
        /// </summary>
        internal static string enter_emoji {
            get {
                return ResourceManager.GetString("enter_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите только одну эмоцию!.
        /// </summary>
        internal static string enter_only_one_emoji {
            get {
                return ResourceManager.GetString("enter_only_one_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите только эмоцию.
        /// </summary>
        internal static string please_enter_emoji {
            get {
                return ResourceManager.GetString("please_enter_emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость:.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установите фильтры кнопками ниже:.
        /// </summary>
        internal static string select_filter {
            get {
                return ResourceManager.GetString("select_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка:.
        /// </summary>
        internal static string sorting {
            get {
                return ResourceManager.GetString("sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветственное сообщение.
        /// </summary>
        internal static string start_message {
            get {
                return ResourceManager.GetString("start_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тир:.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
    }
}
