//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить стикер с вотеркой.
        /// </summary>
        internal static string add_for_sale_sticker {
            get {
                return ResourceManager.GetString("add_for_sale_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить стикер.
        /// </summary>
        internal static string add_sticker {
            get {
                return ResourceManager.GetString("add_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить обложку набора.
        /// </summary>
        internal static string add_sticker_preview {
            get {
                return ResourceManager.GetString("add_sticker_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлено стикеров.
        /// </summary>
        internal static string added_stickers {
            get {
                return ResourceManager.GetString("added_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔕.
        /// </summary>
        internal static string alert_off {
            get {
                return ResourceManager.GetString("alert_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔔.
        /// </summary>
        internal static string alert_on {
            get {
                return ResourceManager.GetString("alert_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления 🔔.
        /// </summary>
        internal static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀.
        /// </summary>
        internal static string arrow_left {
            get {
                return ResourceManager.GetString("arrow_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶.
        /// </summary>
        internal static string arrow_right {
            get {
                return ResourceManager.GetString("arrow_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аукцион.
        /// </summary>
        internal static string auction {
            get {
                return ResourceManager.GetString("auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пак художника.
        /// </summary>
        internal static string buy_author {
            get {
                return ResourceManager.GetString("buy_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить монеты.
        /// </summary>
        internal static string buy_coins {
            get {
                return ResourceManager.GetString("buy_coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить алмазы.
        /// </summary>
        internal static string buy_gems {
            get {
                return ResourceManager.GetString("buy_gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💎 Купить алмазы 💎.
        /// </summary>
        internal static string buy_gems_button {
            get {
                return ResourceManager.GetString("buy_gems_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить ещё.
        /// </summary>
        internal static string buy_more {
            get {
                return ResourceManager.GetString("buy_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить пак.
        /// </summary>
        internal static string buy_pack {
            get {
                return ResourceManager.GetString("buy_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычный пак.
        /// </summary>
        internal static string buy_random {
            get {
                return ResourceManager.GetString("buy_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер копилки увеличен:.
        /// </summary>
        internal static string cash_capacity_increased {
            get {
                return ResourceManager.GetString("cash_capacity_increased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный канал: {0}
        ///Приз: {1}
        ///Общее количество призов: {2}шт.
        ///Время начала раздачи: {3}.
        /// </summary>
        internal static string channel_giveaway_template {
            get {
                return ResourceManager.GetString("channel_giveaway_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите канал.
        /// </summary>
        internal static string choose_channel {
            get {
                return ResourceManager.GetString("choose_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать стикер.
        /// </summary>
        internal static string choose_sticker {
            get {
                return ResourceManager.GetString("choose_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забрать награду {0}.
        /// </summary>
        internal static string claim_prize {
            get {
                return ResourceManager.GetString("claim_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰.
        /// </summary>
        internal static string coin {
            get {
                return ResourceManager.GetString("coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собрать.
        /// </summary>
        internal static string collect {
            get {
                return ResourceManager.GetString("collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция.
        /// </summary>
        internal static string collection {
            get {
                return ResourceManager.GetString("collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединить.
        /// </summary>
        internal static string combine {
            get {
                return ResourceManager.GetString("combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совершить обмен.
        /// </summary>
        internal static string confirm_exchange {
            get {
                return ResourceManager.GetString("confirm_exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить вход.
        /// </summary>
        internal static string confirm_login {
            get {
                return ResourceManager.GetString("confirm_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить обложку.
        /// </summary>
        internal static string confirm_preview {
            get {
                return ResourceManager.GetString("confirm_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель управления.
        /// </summary>
        internal static string control_panel {
            get {
                return ResourceManager.GetString("control_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎁 Создать раздачу 🎁.
        /// </summary>
        internal static string create_giveaway {
            get {
                return ResourceManager.GetString("create_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ-5 по опыту.
        /// </summary>
        internal static string daily_exp_top {
            get {
                return ResourceManager.GetString("daily_exp_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогр. еж. задания.
        /// </summary>
        internal static string daily_task_progress {
            get {
                return ResourceManager.GetString("daily_task_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еж. задания.
        /// </summary>
        internal static string daily_tasks {
            get {
                return ResourceManager.GetString("daily_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заменить стикер.
        /// </summary>
        internal static string edit_sticker {
            get {
                return ResourceManager.GetString("edit_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эффект.
        /// </summary>
        internal static string effect {
            get {
                return ResourceManager.GetString("effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмоция.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить загрузку стикеров.
        /// </summary>
        internal static string end_sticker_upload {
            get {
                return ResourceManager.GetString("end_sticker_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to опыта.
        /// </summary>
        internal static string exp {
            get {
                return ResourceManager.GetString("exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол. опыта.
        /// </summary>
        internal static string exp_gain {
            get {
                return ResourceManager.GetString("exp_gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💎.
        /// </summary>
        internal static string gem {
            get {
                return ResourceManager.GetString("gem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После покупки вы получите {0} алмазов на свой счет..
        /// </summary>
        internal static string gems_description {
            get {
                return ResourceManager.GetString("gems_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}💎 за ₽{1}.
        /// </summary>
        internal static string gems_title {
            get {
                return ResourceManager.GetString("gems_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎁.
        /// </summary>
        internal static string gift {
            get {
                return ResourceManager.GetString("gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шт..
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход на сайт.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗓Логи пользователей🗓.
        /// </summary>
        internal static string logs_menu {
            get {
                return ResourceManager.GetString("logs_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои паки.
        /// </summary>
        internal static string my_packs {
            get {
                return ResourceManager.GetString("my_packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to →.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть пак художника.
        /// </summary>
        internal static string open_author {
            get {
                return ResourceManager.GetString("open_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть ещё.
        /// </summary>
        internal static string open_more {
            get {
                return ResourceManager.GetString("open_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть паки.
        /// </summary>
        internal static string open_packs {
            get {
                return ResourceManager.GetString("open_packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть обычный пак.
        /// </summary>
        internal static string open_random {
            get {
                return ResourceManager.GetString("open_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть авторский пак.
        /// </summary>
        internal static string open_specific {
            get {
                return ResourceManager.GetString("open_specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи открыли этот пак за все время:.
        /// </summary>
        internal static string opened_count {
            get {
                return ResourceManager.GetString("opened_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to паков.
        /// </summary>
        internal static string packs {
            get {
                return ResourceManager.GetString("packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за.
        /// </summary>
        internal static string per {
            get {
                return ResourceManager.GetString("per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наполн. копилки.
        /// </summary>
        internal static string piggy_bank_capacity {
            get {
                return ResourceManager.GetString("piggy_bank_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В подарок вы получите.
        /// </summary>
        internal static string prize {
            get {
                return ResourceManager.GetString("prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайный.
        /// </summary>
        internal static string random_author {
            get {
                return ResourceManager.GetString("random_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из данного пака есть шанс получить абсолютно любой стикер любого автора!.
        /// </summary>
        internal static string random_author_description {
            get {
                return ResourceManager.GetString("random_author_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайный пак.
        /// </summary>
        internal static string random_pack {
            get {
                return ResourceManager.GetString("random_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено случайных паков:.
        /// </summary>
        internal static string random_packs_added {
            get {
                return ResourceManager.GetString("random_packs_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайный стикер.
        /// </summary>
        internal static string random_sticker {
            get {
                return ResourceManager.GetString("random_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получен стикер:.
        /// </summary>
        internal static string random_sticker_added {
            get {
                return ResourceManager.GetString("random_sticker_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуть с аукциона.
        /// </summary>
        internal static string return_from_auction {
            get {
                return ResourceManager.GetString("return_from_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать другой стикер.
        /// </summary>
        internal static string select_another {
            get {
                return ResourceManager.GetString("select_another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный стикер.
        /// </summary>
        internal static string selected_sticker {
            get {
                return ResourceManager.GetString("selected_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выставить на аукцион.
        /// </summary>
        internal static string sell_on_auction {
            get {
                return ResourceManager.GetString("sell_on_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить стикер.
        /// </summary>
        internal static string send_sticker {
            get {
                return ResourceManager.GetString("send_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать пример.
        /// </summary>
        internal static string show_sample {
            get {
                return ResourceManager.GetString("show_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать стикеры.
        /// </summary>
        internal static string show_stickers {
            get {
                return ResourceManager.GetString("show_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать продавцов.
        /// </summary>
        internal static string show_traders {
            get {
                return ResourceManager.GetString("show_traders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать пользователей.
        /// </summary>
        internal static string show_users {
            get {
                return ResourceManager.GetString("show_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустить.
        /// </summary>
        internal static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальные предложения .
        /// </summary>
        internal static string special_offers {
            get {
                return ResourceManager.GetString("special_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭐.
        /// </summary>
        internal static string star {
            get {
                return ResourceManager.GetString("star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стикер.
        /// </summary>
        internal static string sticker {
            get {
                return ResourceManager.GetString("sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эфф. стикеров.
        /// </summary>
        internal static string sticker_effects {
            get {
                return ResourceManager.GetString("sticker_effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стикеров.
        /// </summary>
        internal static string stickers {
            get {
                return ResourceManager.GetString("stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить.
        /// </summary>
        internal static string stop_bot {
            get {
                return ResourceManager.GetString("stop_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тир.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тира.
        /// </summary>
        internal static string tier2 {
            get {
                return ResourceManager.GetString("tier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания акции:.
        /// </summary>
        internal static string time_limit {
            get {
                return ResourceManager.GetString("time_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продавец.
        /// </summary>
        internal static string trader {
            get {
                return ResourceManager.GetString("trader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бессрочно.
        /// </summary>
        internal static string unexpired {
            get {
                return ResourceManager.GetString("unexpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить стикерпак.
        /// </summary>
        internal static string upload_stickerpack {
            get {
                return ResourceManager.GetString("upload_stickerpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
