//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить стикер.
        /// </summary>
        internal static string add_sticker {
            get {
                return ResourceManager.GetString("add_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлено стикеров.
        /// </summary>
        internal static string added_stickers {
            get {
                return ResourceManager.GetString("added_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аукцион.
        /// </summary>
        internal static string auction {
            get {
                return ResourceManager.GetString("auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰.
        /// </summary>
        internal static string coin {
            get {
                return ResourceManager.GetString("coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собрать.
        /// </summary>
        internal static string collect {
            get {
                return ResourceManager.GetString("collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собрать прибыль.
        /// </summary>
        internal static string collect_income {
            get {
                return ResourceManager.GetString("collect_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция.
        /// </summary>
        internal static string collection {
            get {
                return ResourceManager.GetString("collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объединить.
        /// </summary>
        internal static string combine {
            get {
                return ResourceManager.GetString("combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить стикерпак.
        /// </summary>
        internal static string download_stickerpack {
            get {
                return ResourceManager.GetString("download_stickerpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмоция.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💎.
        /// </summary>
        internal static string gem {
            get {
                return ResourceManager.GetString("gem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шт..
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to →.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за.
        /// </summary>
        internal static string per {
            get {
                return ResourceManager.GetString("per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать другой стикер.
        /// </summary>
        internal static string select_another {
            get {
                return ResourceManager.GetString("select_another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выставить на аукцион.
        /// </summary>
        internal static string sell_on_auction {
            get {
                return ResourceManager.GetString("sell_on_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить стикер.
        /// </summary>
        internal static string send_sticker {
            get {
                return ResourceManager.GetString("send_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример.
        /// </summary>
        internal static string show_sample {
            get {
                return ResourceManager.GetString("show_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать стикеры.
        /// </summary>
        internal static string show_stickers {
            get {
                return ResourceManager.GetString("show_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать продавцов.
        /// </summary>
        internal static string show_traders {
            get {
                return ResourceManager.GetString("show_traders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭐.
        /// </summary>
        internal static string star {
            get {
                return ResourceManager.GetString("star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стикер.
        /// </summary>
        internal static string sticker {
            get {
                return ResourceManager.GetString("sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тир.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
