//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCollector.Commands.CallbackQueryHandler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CallbackQueryCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CallbackQueryCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCollector.Commands.CallbackQueryHandler.CallbackQueryCommands", typeof(CallbackQueryCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACZ.
        /// </summary>
        internal static string add_puzzle {
            get {
                return ResourceManager.GetString("add_puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA.
        /// </summary>
        internal static string add_sticker_preview {
            get {
                return ResourceManager.GetString("add_sticker_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAB.
        /// </summary>
        internal static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAC.
        /// </summary>
        internal static string authors_menu {
            get {
                return ResourceManager.GetString("authors_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAD.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACJ.
        /// </summary>
        internal static string beginners_tasks {
            get {
                return ResourceManager.GetString("beginners_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAE.
        /// </summary>
        internal static string buy_coins {
            get {
                return ResourceManager.GetString("buy_coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAF.
        /// </summary>
        internal static string buy_gems {
            get {
                return ResourceManager.GetString("buy_gems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAG.
        /// </summary>
        internal static string buy_pack {
            get {
                return ResourceManager.GetString("buy_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAH.
        /// </summary>
        internal static string buy_shop_item {
            get {
                return ResourceManager.GetString("buy_shop_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAI.
        /// </summary>
        internal static string buy_sticker {
            get {
                return ResourceManager.GetString("buy_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL.
        /// </summary>
        internal static string check_distribution {
            get {
                return ResourceManager.GetString("check_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAJ.
        /// </summary>
        internal static string choose_pack {
            get {
                return ResourceManager.GetString("choose_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACB.
        /// </summary>
        internal static string claim_giveaway {
            get {
                return ResourceManager.GetString("claim_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAK.
        /// </summary>
        internal static string collect_income {
            get {
                return ResourceManager.GetString("collect_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAL.
        /// </summary>
        internal static string combine {
            get {
                return ResourceManager.GetString("combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAM.
        /// </summary>
        internal static string combine_stickers {
            get {
                return ResourceManager.GetString("combine_stickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAN.
        /// </summary>
        internal static string confirm_buying {
            get {
                return ResourceManager.GetString("confirm_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAO.
        /// </summary>
        internal static string confirm_exchange {
            get {
                return ResourceManager.GetString("confirm_exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABY.
        /// </summary>
        internal static string confirm_giveaway {
            get {
                return ResourceManager.GetString("confirm_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAP.
        /// </summary>
        internal static string confirm_login {
            get {
                return ResourceManager.GetString("confirm_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAQ.
        /// </summary>
        internal static string confirm_selling {
            get {
                return ResourceManager.GetString("confirm_selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAR.
        /// </summary>
        internal static string control_panel {
            get {
                return ResourceManager.GetString("control_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAS.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACK.
        /// </summary>
        internal static string create_distribution {
            get {
                return ResourceManager.GetString("create_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABW.
        /// </summary>
        internal static string create_giveaway {
            get {
                return ResourceManager.GetString("create_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACQ.
        /// </summary>
        internal static string create_inline_button {
            get {
                return ResourceManager.GetString("create_inline_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACP.
        /// </summary>
        internal static string create_url_button {
            get {
                return ResourceManager.GetString("create_url_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAT.
        /// </summary>
        internal static string daily_tasks {
            get {
                return ResourceManager.GetString("daily_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAU.
        /// </summary>
        internal static string delete_combine {
            get {
                return ResourceManager.GetString("delete_combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAV.
        /// </summary>
        internal static string edit_sticker {
            get {
                return ResourceManager.GetString("edit_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACY.
        /// </summary>
        internal static string edit_stickerpack {
            get {
                return ResourceManager.GetString("edit_stickerpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAW.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAX.
        /// </summary>
        internal static string end_sticker_upload {
            get {
                return ResourceManager.GetString("end_sticker_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACE.
        /// </summary>
        internal static string group_claim_giveaway {
            get {
                return ResourceManager.GetString("group_claim_giveaway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.
        /// </summary>
        internal static string group_claim_ladder {
            get {
                return ResourceManager.GetString("group_claim_ladder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        internal static string ignore {
            get {
                return ResourceManager.GetString("ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACF.
        /// </summary>
        internal static string invite_friend {
            get {
                return ResourceManager.GetString("invite_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACV.
        /// </summary>
        internal static string join_puzzle {
            get {
                return ResourceManager.GetString("join_puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAY.
        /// </summary>
        internal static string logs_menu {
            get {
                return ResourceManager.GetString("logs_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAZ.
        /// </summary>
        internal static string my_packs {
            get {
                return ResourceManager.GetString("my_packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABA.
        /// </summary>
        internal static string open_author_pack_menu {
            get {
                return ResourceManager.GetString("open_author_pack_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABB.
        /// </summary>
        internal static string open_pack {
            get {
                return ResourceManager.GetString("open_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC.
        /// </summary>
        internal static string pack_info {
            get {
                return ResourceManager.GetString("pack_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACW.
        /// </summary>
        internal static string puzzle_supergame {
            get {
                return ResourceManager.GetString("puzzle_supergame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABD.
        /// </summary>
        internal static string return_from_auction {
            get {
                return ResourceManager.GetString("return_from_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABE.
        /// </summary>
        internal static string select_for_sale_pack {
            get {
                return ResourceManager.GetString("select_for_sale_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACA.
        /// </summary>
        internal static string select_giveaway_tier {
            get {
                return ResourceManager.GetString("select_giveaway_tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABF.
        /// </summary>
        internal static string select_order {
            get {
                return ResourceManager.GetString("select_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABG.
        /// </summary>
        internal static string select_price {
            get {
                return ResourceManager.GetString("select_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABH.
        /// </summary>
        internal static string select_provider {
            get {
                return ResourceManager.GetString("select_provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI.
        /// </summary>
        internal static string select_shop_pack {
            get {
                return ResourceManager.GetString("select_shop_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABJ.
        /// </summary>
        internal static string sell_sticker {
            get {
                return ResourceManager.GetString("sell_sticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACN.
        /// </summary>
        internal static string send_distribution_to_groups {
            get {
                return ResourceManager.GetString("send_distribution_to_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACM.
        /// </summary>
        internal static string send_distribution_to_private {
            get {
                return ResourceManager.GetString("send_distribution_to_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACO.
        /// </summary>
        internal static string send_distribution_to_private_and_groups {
            get {
                return ResourceManager.GetString("send_distribution_to_private_and_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACD.
        /// </summary>
        internal static string send_rules {
            get {
                return ResourceManager.GetString("send_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABK.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACR.
        /// </summary>
        internal static string set_distribution_button_value {
            get {
                return ResourceManager.GetString("set_distribution_button_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABM.
        /// </summary>
        internal static string set_exchange_sum {
            get {
                return ResourceManager.GetString("set_exchange_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABN.
        /// </summary>
        internal static string set_gems_sum {
            get {
                return ResourceManager.GetString("set_gems_sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABX.
        /// </summary>
        internal static string set_giveaway_prize {
            get {
                return ResourceManager.GetString("set_giveaway_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABL.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACI.
        /// </summary>
        internal static string share_invite_url {
            get {
                return ResourceManager.GetString("share_invite_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACH.
        /// </summary>
        internal static string show_invite_reward_info {
            get {
                return ResourceManager.GetString("show_invite_reward_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACG.
        /// </summary>
        internal static string show_invited_friends {
            get {
                return ResourceManager.GetString("show_invited_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABO.
        /// </summary>
        internal static string show_order_info {
            get {
                return ResourceManager.GetString("show_order_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABP.
        /// </summary>
        internal static string show_sample {
            get {
                return ResourceManager.GetString("show_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABQ.
        /// </summary>
        internal static string show_top_by {
            get {
                return ResourceManager.GetString("show_top_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABZ.
        /// </summary>
        internal static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABR.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS.
        /// </summary>
        internal static string special_offers {
            get {
                return ResourceManager.GetString("special_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACU.
        /// </summary>
        internal static string start_puzzle {
            get {
                return ResourceManager.GetString("start_puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACC.
        /// </summary>
        internal static string start_roulette {
            get {
                return ResourceManager.GetString("start_roulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABT.
        /// </summary>
        internal static string stop_bot {
            get {
                return ResourceManager.GetString("stop_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABU.
        /// </summary>
        internal static string tier {
            get {
                return ResourceManager.GetString("tier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS.
        /// </summary>
        internal static string upload_pack_gif_preview {
            get {
                return ResourceManager.GetString("upload_pack_gif_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABV.
        /// </summary>
        internal static string upload_stickerpack {
            get {
                return ResourceManager.GetString("upload_stickerpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACX.
        /// </summary>
        internal static string upload_stickerpack_beta {
            get {
                return ResourceManager.GetString("upload_stickerpack_beta", resourceCulture);
            }
        }
    }
}
